Assignment5/Pages/Shopping.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Assignment5.Infrastructure;
using Assignment5.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Assignment5.Pages
{
    public class ShoppingModel : PageModel
    {
        private iBookstoreRepository repository;

        //Constructor

        public ShoppingModel (iBookstoreRepository repo, Cart cartService)
        {
            repository = repo;

            Cart = cartService;
        }

        //Properties

        public Cart Cart { get; set; }

        public string ReturnUrl { get; set; }

        //Methods

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(long bookId, string returnUrl)
        {
            Book book = repository.Books.FirstOrDefault(p => p.BookId == bookId);

            Cart.AddItem(book, 1);

            HttpContext.Session.SetJson("cart", Cart);

            return RedirectToPage(new { returnUrl = returnUrl });
        }
        public IActionResult OnPostRemove(long BookId, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(cl =>
                cl.Book.BookId == BookId).Book);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

Assignment5/Pages/Shopping.cshtml
@page

@model Assignment5.Pages.ShoppingModel

@{
}

<h2>Your Cart</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Book</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Subtotal</th>
        </tr>

    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
        <tr>
            <td class="text-left">@line.Book.Title</td>
            <td class="text-center">@line.Quantity</td>
            <td class="text-right">$@line.Book.Price</td>
            <td class="text-right">@((line.Quantity * line.Book.Price).ToString("c", System.Globalization.CultureInfo.GetCultureInfo("en-us")))</td>

            <td class="text-center">
                <form asp-page-handler="Remove" method="post">
                    <input type="hidden" name="BookID"
                           value="@line.Book.BookId" />
                    <input type="hidden" name="returnUrl"
                           value="@Model.ReturnUrl" />
                    <button type="submit" class="btn btn-sm btn-danger">
                        Remove
                    </button>
                </form>
            </td>
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">@Model.Cart.ComputeTotalSum().ToString("c", System.Globalization.CultureInfo.GetCultureInfo("en-us"))</td>
        </tr>
    </tfoot>

</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
</div>