Assignment5/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Assignment5.Models;
namespace Assignment5.Components
{// Cart Summary
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Assignment5/Components/NavigationMenuViewComponent.cs
using System;
using System.Linq;
using Assignment5.Models;
using Microsoft.AspNetCore.Mvc;

namespace Assignment5.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {//Select Categories
        private iBookstoreRepository repository;

        public NavigationMenuViewComponent(iBookstoreRepository r)
        {
            repository = r;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];

            return View(repository.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

Assignment5/Views/Shared/ProjectSummary.cshtml
@model Book
<div class="card card-outline-primary m-1 p-1 text-center" style="width: 40rem;">
    <div class="bg-faded p-1">
        <h4>Book Title: @Model.Title</h4>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Author First Name: @Model.AuthorFirstName</li>
            <li class="list-group-item">Author Last Name: @Model.AuthorLastName</li>
            <li class="list-group-item">Publisher: @Model.Publisher</li>
            <li class="list-group-item">ISBN: @Model.ISBN</li>
            <li class="list-group-item">Classification: @Model.Classification</li>
            <li class="list-group-item">Category: @Model.Category</li>
            <li class="list-group-item">Price: $@Model.Price</li>
            <li class="list-group-item">Pages: @Model.PageNum</li>
        </ul>
    </div>
    <form id="@Model.BookId" asp-page="/Shopping" method="post">
        <input type="hidden" asp-for="BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            @Model.Title
            <button type="submit" class="btn-success btn-sm pull-right" style="float:right">
                Add to Cart
            </button>
        </span>

    </form>
</div>

Assignment5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Assignment 6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>
    <!--Formatting of the data-->

    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">BOOK STORE</div>
                <div class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            <vc:navigation-menu />
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>